[tool.poetry]
name = "mxnet_example"
version = "0.1.0"
description = "MXNet example with MNIST and CNN"
authors = ["The Flower Authors <enquiries@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.6.2"
flwr = "^0.15.0"  # For development: { path = "../../", develop = true }
mxnet = "^1.7.0"

[build-system]
requires = ["poetry-core==1.1.4"]
build-backend = "poetry.core.masonry.api"
